_target_: pytorch_lightning.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 10 # prevents early stopping
max_epochs: 120

accelerator: gpu
devices: 1

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1