defaults:
  - model_checkpoint.yaml
  # - early_stopping.yaml
  # - model_summary.yaml
  # - rich_progress_bar.yaml
  # - learning_rate_monitor.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir} ## Added in <cid>/<round>/checkpoints/
  filename: "last"
  #monitor: "val/loss"
  #mode: "min"
  save_last: False
  auto_insert_metric_name: False

# early_stopping:
#   monitor: "val/loss"
#   patience: 10
#   mode: "min"

# model_summary:
#   max_depth: -1
