defaults:
  - client: fed_client
  - strategy: fed_avg
  - server: server_config
  - extras: default.yaml
  - hydra: fed_hydra.yaml
  - partitions: volume
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir} ## Added in <cid>/<round>/checkpoints/
  filename: "epoch_{epoch:03d}"
  save_last: True
  auto_insert_metric_name: False

datamodule:
  batch_size: 64
  
task_name: "fed_chexpert"

pool_size: 10

client_resources:
  num_cpus: 8
  num_gpus: 0.3

ray_init_args:
  include_dashboard: False

strategy:
  fraction_fit: 1.0
  fraction_evaluate: 1.0
  min_fit_clients : 1
  min_evaluate_clients: 1
  min_available_clients: 1
  accept_failures: True

server_config:
  _target_: flwr.server.ServerConfig
  num_rounds: 5

client_config_name: 'client/fed_prod_client'

job_name: "xyz"

sample_percent: 1