_target_: src.datamodules.chexpert_datamodule.CheXpertDataModule
batch_size: 256
num_workers: 24
pin_memory: True
policy: 'one'
train_fname: '/scratch/tm3647/public/MLH/chexpert_dataset/train.csv'
val_fname: '/scratch/tm3647/public/MLH/chexpert_dataset/valid.csv'
test_fname: ''
train_val_split: [0.9775,0.0225]
normalize_mean_values: [0.398,0.398,0.398] #Mimic-cxr
normalize_std_values: [0.327, 0.327, 0.327] #Mimic-cxr