_target_: src.datamodules.chexpert_datamodule.CheXpertDataModule
batch_size: 256
num_workers: 24
pin_memory: True
policy: 'one'
root_dir: '/'
train_fname: '/scratch/tm3647/public/MLH/chexpert_dataset/train.csv'
val_fname: '/scratch/tm3647/public/MLH/chexpert_dataset/valid.csv'
test_fname: ''
train_val_split: [0.9775,0.0225]